Name: Krishna GSVV  
Roll no. AV.EN.U4CSE22016  
Date: 13/8/24  

In [2]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [26]:
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])
result = np.add(arr1, arr2)
print(result)

[11 22 33 44 55]


In [4]:
import numpy as np
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([1, 2, 3, 4, 5])
result = np.subtract(arr1, arr2)
print(result)

[ 9 18 27 36 45]


In [9]:
import numpy as np
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([1, 2, 3, 4, 5])
result = np.multiply(arr1, arr2)
print(result)

[ 10  40  90 160 250]


In [13]:
import numpy as np
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([1, 2, 3, 4, 5])
result = np.divide(arr1, arr2)
print(result)

[10. 10. 10. 10. 10.]


In [17]:
import numpy as np
arr = np.array([4, 9, 16, 25, 36])
result = np.sqrt(arr)
print(result)

[2. 3. 4. 5. 6.]


In [18]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
result = np.exp(arr)
print(result)

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [19]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
result = np.sum(arr)
print(result)

15


In [20]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
result = np.any(arr)
print(result)

True


In [21]:
import numpy as np
arr = np.array([0, 2, 3, 4, 5])
result = np.all(arr)
print(result)

False


In [23]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(np.mean(arr))

3.0


In [24]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(np.median(arr))

3.0


In [39]:
import numpy as np
import statistics
arr = np.array([1, 1, 3, 4, 5])
print(sd.mode(arr))

1


In [28]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(np.log(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [29]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(np.diff(arr))

[1 1 1 1]


In [30]:
import numpy as np
arr = np.array([1.9, 2, 3, 4, 5])
print(np.round(arr))

[2. 2. 3. 4. 5.]


In [31]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(np.cumsum(arr))

[ 1  3  6 10 15]


In [32]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(np.cumprod(arr))

[  1   2   6  24 120]


In [33]:
import numpy as np
arr = np.array([10, 2, 3, 4, 5])
print(np.sort(arr))

[ 2  3  4  5 10]


In [37]:
import numpy as np
arr = np.array([5, 4, 13, 2, 11])
sorted_arr = np.sort(arr)[::-1]
print(sorted_arr)

[13 11  5  4  2]


In [1]:
from datascience import Table
Table()

In [3]:
Table().with_columns('Number of petals', [8,34,5], 'Name', ['harshi','lilly','rosie'])

Number of petals | Name
8                | harshi
34               | lilly
5                | rosie

In [4]:
ran= Table.read_table('ran.csv')
ran

Longitude | Latitude | City        | Direction | Survivors
32        | 54.8     | Smolensk    | Advance   | 145000
33.2      | 54.9     | Dorogobouge | Advance   | 140000
34.4      | 55.5     | Chjat       | Advance   | 127100
37.6      | 55.8     | Moscou      | Advance   | 100000
34.3      | 55.2     | Wixma       | Retreat   | 55000
32        | 54.6     | Smolensk    | Retreat   | 24000
30.4      | 54.4     | Orscha      | Retreat   | 20000
26.8      | 54.3     | Moiodexno   | Retreat   | 12000

In [5]:
ran.num_rows

8

In [6]:
ran.labels

('Longitude', 'Latitude', 'City', 'Direction', 'Survivors')

In [7]:
ran.relabeled('City', 'City Name')

Longitude | Latitude | City Name   | Direction | Survivors
32        | 54.8     | Smolensk    | Advance   | 145000
33.2      | 54.9     | Dorogobouge | Advance   | 140000
34.4      | 55.5     | Chjat       | Advance   | 127100
37.6      | 55.8     | Moscou      | Advance   | 100000
34.3      | 55.2     | Wixma       | Retreat   | 55000
32        | 54.6     | Smolensk    | Retreat   | 24000
30.4      | 54.4     | Orscha      | Retreat   | 20000
26.8      | 54.3     | Moiodexno   | Retreat   | 12000

In [8]:
ran

Longitude | Latitude | City        | Direction | Survivors
32        | 54.8     | Smolensk    | Advance   | 145000
33.2      | 54.9     | Dorogobouge | Advance   | 140000
34.4      | 55.5     | Chjat       | Advance   | 127100
37.6      | 55.8     | Moscou      | Advance   | 100000
34.3      | 55.2     | Wixma       | Retreat   | 55000
32        | 54.6     | Smolensk    | Retreat   | 24000
30.4      | 54.4     | Orscha      | Retreat   | 20000
26.8      | 54.3     | Moiodexno   | Retreat   | 12000

In [9]:
ran.column('Survivors')

array([145000, 140000, 127100, 100000,  55000,  24000,  20000,  12000])

In [10]:
ran.column(4)

array([145000, 140000, 127100, 100000,  55000,  24000,  20000,  12000])

In [11]:
ran.column(4).item(0)

145000

In [12]:
ran.column(4).item(5)

24000

In [13]:
initial = ran.column('Survivors').item(0)
minard = ran.with_columns(
'Percent Surviving',ran.column('Survivors')/initial
)
minard

Longitude | Latitude | City        | Direction | Survivors | Percent Surviving
32        | 54.8     | Smolensk    | Advance   | 145000    | 1
33.2      | 54.9     | Dorogobouge | Advance   | 140000    | 0.965517
34.4      | 55.5     | Chjat       | Advance   | 127100    | 0.876552
37.6      | 55.8     | Moscou      | Advance   | 100000    | 0.689655
34.3      | 55.2     | Wixma       | Retreat   | 55000     | 0.37931
32        | 54.6     | Smolensk    | Retreat   | 24000     | 0.165517
30.4      | 54.4     | Orscha      | Retreat   | 20000     | 0.137931
26.8      | 54.3     | Moiodexno   | Retreat   | 12000     | 0.0827586

In [14]:
ran.select('Longitude', 'Latitude')

Longitude | Latitude
32        | 54.8
33.2      | 54.9
34.4      | 55.5
37.6      | 55.8
34.3      | 55.2
32        | 54.6
30.4      | 54.4
26.8      | 54.3

In [15]:
ran.select(0, 1)

Longitude | Latitude
32        | 54.8
33.2      | 54.9
34.4      | 55.5
37.6      | 55.8
34.3      | 55.2
32        | 54.6
30.4      | 54.4
26.8      | 54.3

In [16]:
ran.select('Survivors')

Survivors
145000
140000
127100
100000
55000
24000
20000
12000

In [17]:
ran.column('Survivors')

array([145000, 140000, 127100, 100000,  55000,  24000,  20000,  12000])

In [18]:
ran.drop('Longitude', 'Latitude', 'Direction')

City        | Survivors
Smolensk    | 145000
Dorogobouge | 140000
Chjat       | 127100
Moscou      | 100000
Wixma       | 55000
Smolensk    | 24000
Orscha      | 20000
Moiodexno   | 12000

In [19]:
import pandas as pd
data =pd.read_csv("nba.csv",index_col="Name")
print(data)
data.shape

                         Team  Number Position   Age Height  Weight  \
Name                                                                  
Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0   
Jae Crowder    Boston Celtics    99.0       SF  25.0    6-6   235.0   
John Holland   Boston Celtics    30.0       SG  27.0    6-5   205.0   
R.J. Hunter    Boston Celtics    28.0       SG  22.0    6-5   185.0   
Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0   
...                       ...     ...      ...   ...    ...     ...   
Shelvin Mack        Utah Jazz     8.0       PG  26.0    6-3   203.0   
Raul Neto           Utah Jazz    25.0       PG  24.0    6-1   179.0   
Tibor Pleiss        Utah Jazz    21.0        C  26.0    7-3   256.0   
Jeff Withey         Utah Jazz    24.0        C  26.0    7-0   231.0   
NaN                       NaN     NaN      NaN   NaN    NaN     NaN   

                         College     Salary  
Name                          

(458, 8)

In [20]:
import pandas as pd
data =pd.read_csv("nba.csv",index_col="Name")
print(data)
data.shape

                         Team  Number Position   Age Height  Weight  \
Name                                                                  
Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0   
Jae Crowder    Boston Celtics    99.0       SF  25.0    6-6   235.0   
John Holland   Boston Celtics    30.0       SG  27.0    6-5   205.0   
R.J. Hunter    Boston Celtics    28.0       SG  22.0    6-5   185.0   
Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0   
...                       ...     ...      ...   ...    ...     ...   
Shelvin Mack        Utah Jazz     8.0       PG  26.0    6-3   203.0   
Raul Neto           Utah Jazz    25.0       PG  24.0    6-1   179.0   
Tibor Pleiss        Utah Jazz    21.0        C  26.0    7-3   256.0   
Jeff Withey         Utah Jazz    24.0        C  26.0    7-0   231.0   
NaN                       NaN     NaN      NaN   NaN    NaN     NaN   

                         College     Salary  
Name                          

(458, 8)