Date: 13th August, 2024

### What is NumPy?
NumPy is a powerful library for numerical computing in Python. It provides support for arrays, matrices, and many mathematical functions to operate on these data structures efficiently. NumPy is widely used in scientific computing, data analysis, and machine learning.

### Key Features of NumPy:
1. **N-Dimensional Array Object**: Provides a powerful N-dimensional array object.
2. **Broadcasting**: Supports broadcasting, which allows arithmetic operations on arrays of different shapes.
3. **Mathematical Functions**: Includes a large collection of mathematical functions to operate on arrays.
4. **Linear Algebra**: Provides tools for linear algebra, Fourier transforms, and random number generation.
5. **Performance**: Highly optimized for performance with operations implemented in C.

### Initiation and Basic Usage of NumPy Arrays

#### Creating NumPy Arrays
You can create NumPy arrays in several ways:

1. **From a Python List**:
    ```python
    # Creating a 1D array
    arr1 = np.array([1, 2, 3, 4, 5])
    print(arr1)

    # Creating a 2D array
    arr2 = np.array([[1, 2, 3], [4, 5, 6]])
    print(arr2)
    ```

2. **Using Built-in Functions**:
    ```python
    # Creating an array of zeros
    zeros = np.zeros((3, 3))
    print(zeros)

    # Creating an array of ones
    ones = np.ones((2, 4))
    print(ones)

    # Creating an array with a range of values
    range_arr = np.arange(0, 10, 2)
    print(range_arr)

    # Creating an array with evenly spaced values
    linspace_arr = np.linspace(0, 1, 5)
    print(linspace_arr)
    ```

3. **Random Arrays**:
    ```python
    # Creating an array with random values
    random_arr = np.random.rand(3, 3)
    print(random_arr)

    # Creating an array with random integers
    random_int_arr = np.random.randint(0, 10, (3, 3))
    print(random_int_arr)
    ```

#### Basic Operations on NumPy Arrays
NumPy supports a variety of operations on arrays:

1. **Arithmetic Operations**:
    ```python
    arr = np.array([1, 2, 3, 4, 5])
    print(arr + 2)  # Add 2 to each element
    print(arr * 3)  # Multiply each element by 3
    ```

2. **Element-wise Operations**:
    ```python
    arr1 = np.array([1, 2, 3])
    arr2 = np.array([4, 5, 6])
    print(arr1 + arr2)  # Element-wise addition
    print(arr1 * arr2)  # Element-wise multiplication
    ```

3. **Matrix Operations**:
    ```python
    mat1 = np.array([[1, 2], [3, 4]])
    mat2 = np.array([[5, 6], [7, 8]])
    print(np.dot(mat1, mat2))  # Matrix multiplication
    ```

4. **Statistical Operations**:
    ```python
    arr = np.array([1, 2, 3, 4, 5])
    print(np.mean(arr))  # Mean
    print(np.sum(arr))   # Sum
    print(np.std(arr))   # Standard deviation
    ```

### Example Usage
Here's a simple example demonstrating the creation and manipulation of a NumPy array:

```python
import numpy as np

# Create a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Print the array
print("Array:")
print(arr)

# Perform arithmetic operations
print("Array + 2:")
print(arr + 2)

# Calculate the mean
print("Mean of the array:")
print(np.mean(arr))

# Matrix multiplication
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])
print("Matrix multiplication:")
print(np.dot(mat1, mat2))
```

This should give you a good starting point for using NumPy and NumPy arrays in your projects.

In [8]:
import numpy as np

a = np.array([11, 2, 34, 54, 13, 24, 4])
b = np.array([3, 4, 5, 6, 7, 8])
print(a)
print(b)

print(a + 2)
print(a * 2)
print(np.mean(a))

sum = np.sum(a)
print(sum)
product = np.prod(a)
print(product)

diff = np.diff(a)
r = np.round(a)
print(r)
cp = np.cumprod(a)
print(cp)
cs = np.cumsum(a)
print(cs)

e = np.exp(a)
print(e)

a = np.log(a)
print(a)

sq = np.sqrt(a)
print(sq)


string_list = ["apple", "banana", "cherry", "date"]
string_array = np.array(string_list)
print(string_array)
print(np.char.lower(string_list))
print(np.char.upper(string_list))
print(np.char.count(string_list, "a"))
print(np.char.find(string_list, "a"))

[11  2 34 54 13 24  4]
[3 4 5 6 7 8]
[13  4 36 56 15 26  6]
[ 22   4  68 108  26  48   8]
20.2857142857
142
50409216
[11  2 34 54 13 24  4]
[      11       22      748    40392   525096 12602304 50409216]
[ 11  13  47 101 114 138 142]
[  5.98741417e+04   7.38905610e+00   5.83461743e+14   2.83075330e+23
   4.42413392e+05   2.64891221e+10   5.45981500e+01]
[ 2.39789527  0.69314718  3.52636052  3.98898405  2.56494936  3.17805383
  1.38629436]
[ 1.54851389  0.83255461  1.87786062  1.99724411  1.60154593  1.78270969
  1.17741002]
['apple' 'banana' 'cherry' 'date']
['apple' 'banana' 'cherry' 'date']
['APPLE' 'BANANA' 'CHERRY' 'DATE']
[1 3 0 1]
[ 0  1 -1  1]


In [9]:
from datascience import Table


flowers = Table().with_columns(
    "Number of petals", [8, 34, 5], "Name", ["rose", "jasmine", "lily"]
)

flowers.show()

In [11]:
from datascience import Table

# Read the CSV file into a Table
minard = Table.read_table(
    r"V:\Code\My Python Life\Python - College\Semester 5\Data Analytics\minard.csv"
)

# Display the first few rows of the table to verify
minard.show()



array([145000, 140000, 127100, 100000,  55000,  24000,  20000,  12000])

The method num_columns gives the number of columns in the table, and num_rows the number of rows.

In [ ]:
minard.column('Survivors')

The method labels can be used to list the labels of all the columns. With minard we don't
gain much by this, but it can be very useful for tables that are so large that not all columns
are visible on the screen.